spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/test-user?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #换成p6spy的驱动

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql语句打印
#  mapper-locations: /com/liangzhicheng/mappers/* #使用xml时，若xml文件与mapper接口文件不在同一目录下，则需要在application.yml中配置mapper.xml的存放路径
  global-config:
    db-config:
      id-type: input #可以针对每个实体类，使用@TableId注解指定该实体类的主键策略，这可以理解为局部策略，若希望对所有的实体类，都采用同一种主键策略，只需要在application.yml进行配置即可，例如配置全局采用手动设置主键策略
      table-prefix: xxx_ #表名前缀
      logic-delete-field: deleted  #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为0）
      #若逻辑已删除和未删除的值和默认值一样，则可以不配置这2项
